name: Sample Grails command
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Gradle
        run: cd complete/ && java -jar grails-wrapper.jar
      # - name: Print Grails help
      #   run: |
      #     ls -la
      #     cd complete
      #     wget -q "https://github.com/grails/grails-core/releases/download/v5.3.2/grails-5.3.2.zip" -O temp.zip
      #     unzip -q temp.zip
      #     grails-5.3.2/bin/grails clean --non-interactive
      #     grails-5.3.2/bin/grails test-app --non-interactive
