name: Sample Grails command
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Grails help
        run: |
          wget -q "https://github.com/grails/grails-core/releases/download/v5.3.2/grails-5.3.2.zip" -O temp.zip
          unzip -q temp.zip
          cd grails-5.3.2/bin/
          ./grails --help
